os: linux
language: node_js
node_js: stable

# assign build branches
branches:
  only:
    - source

# cache this directory
cache:
  directories:
    - node_modules

# S: Build Lifecycle
before_install:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - npm config set registry https://registry.npm.taobao.org
  - cnpm install -g hexo-cli # 安装 hexo
  - cnpm install hexo-renderer-scss hexo-renderer-swig --save
  - git clone https://github.com/ahonn/hexo-theme-even themes/even
  - cp themes/even/_config.yml.example themes/even/_config.yml

install:
  - cnpm install # 安装 package.json 中的插件

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true # 构建完成后不清除
  token: $GITHUB_TOKEN # 你刚刚设置的 token
  keep_history: true # 保存历史
  fqdn: kwaibook.com # 自定义域名，使用 username.github.io 可删除
  on:
    branch: source # hexo 站点源文件所在的 branch
  local_dir: public 
  target_branch: master # 存放生成站点文件的 branch，使用 username.github.io 必须是 master
